import { type ClassNameValue, extendTailwindMerge } from "tailwind-merge";

const twMerge = extendTailwindMerge({
  extend: {
    theme: {
      aspect: ["landscape", "portrait", "square", "video"],
      breakpoint: ["desktop", "wide"],
      color: [
        "accent",
        "accent-soft",
        "bg",
        "bg-alt",
        "border",
        "border-inverse",
        "border-strong",
        "border-subtle",
        "disabled-bg",
        "error",
        "error-soft",
        "focus",
        "focus-inverse",
        "glass",
        "hairline-inverse",
        "info",
        "info-soft",
        "inverse",
        "inverse-2",
        "primary",
        "primary-active",
        "primary-hover",
        "primary-soft",
        "sage",
        "sage-soft",
        "scrim",
        "scrim-strong",
        "secondary",
        "secondary-hover",
        "secondary-soft",
        "sky",
        "sky-soft",
        "success",
        "success-soft",
        "surface",
        "text",
        "text-2",
        "text-disabled",
        "text-inverse",
        "text-inverse-2",
        "text-muted",
        "warning",
        "warning-soft",
      ],
      container: ["page", "text"],
      font: ["display", "mono", "sans"],
      radius: ["lg", "md", "sm"],
      shadow: ["floating", "overlay"],
      spacing: [
        "block",
        "control",
        "group",
        "gutter",
        "header",
        "inset",
        "item",
        "label",
        "section",
        "target",
      ],
    },
  },
});

export function cn(...inputs: ClassNameValue[]): string {
  return twMerge(...inputs);
}
